Repository kiwiproject/kiwi-test, pull requests merged in 2020-11, with the labels that each got.

#158 Fix several deprecation warnings
  src/main/java/org/kiwiproject/test/assertj/jsonassert/JSONAssertSoftAssertions.java
  src/test/java/org/kiwiproject/test/jaxrs/exception/JaxrsExceptionTestHelperTest.java
Labels: documentation, refactoring

#163 Switch from TravisCI tio GitHub Actions for the build
  .github/workflows/build.yml
  .travis.yml.deleteme
  pom.xml
Labels: refactoring

#164 Replace TravisCI badge with GitHub actions badge
  .github/workflows/build.yml
  README.md
Labels: enhancement

#165 Upgrade kiwi from 0.14.0 to 0.15.0
  pom.xml
Labels: dependencies

#166 Fix Sonar projectKey property in the POM to be kiwi-test not kiwi
  pom.xml
Labels: bug
