Repository kiwiproject/kiwi-test, pull requests merged in 2020-10, with the labels that each got.

#98 Replace 3 tests in ServiceNamesTest with a single @ParameterizedTest
  src/test/java/org/kiwiproject/test/util/ServiceNamesTest.java
Labels: code cleanup

#129 Add dependabot config
  .github/dependabot.yml
Labels: dependencies

#137 Update javadoc in H2FileBasedDatabaseExtension
  src/main/java/org/kiwiproject/test/junit/jupiter/H2FileBasedDatabaseExtension.java
  src/test/java/org/kiwiproject/test/junit/jupiter/H2FileBasedDatabaseExtensionRegisterTest.java
Labels: documentation

#143 Fix example code in Javadoc in MongoDbExtension
  src/main/java/org/kiwiproject/test/junit/jupiter/MongoDbExtension.java
Labels: documentation

#146 Rename static final extension fields to UPPER_SNAKE_CASE in tests
  src/test/java/org/kiwiproject/test/junit/jupiter/Jdbi3DaoExtensionTest.java
  src/test/java/org/kiwiproject/test/junit/jupiter/Jdbi3ExtensionTest.java
Labels: code cleanup
